version: "3"

services:
  node3:
    image: blockchain
    container_name: third
    build: . 
    command: python blockchain.py --name node3
    depends_on:
      - node1

  node2:
    image: blockchain
    container_name: second
    build: .  
    command: python blockchain.py --name node2
    depends_on:
      - node1

  node1:
    image: blockchain
    container_name: first
    build: . 
    command: python blockchain.py --name node1 --genesis True
    